### PR TITLE
WSM 8461: Initial documentation check-in

### PR DESCRIPTION
**Pull request by andytael**
Initial documentation check-in

### CODE REVIEW

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please fix the following issues of your PR:
1. Make sure all folders' and files' filenames are lower case
2. Discard changes to the .gitignore and _config.yml files on your local cloned repo
3. Use the [oracle-livelabs.github.io](http://oracle-livelabs.github.io/) links in manifest.json and index.html, instead of learning-library links or object storage links. Refer to files in this directory for examples: https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop/workshops/tenancy
Please refer to the [self QA form](https://objectstorage.us-ashburn-1.oraclecloud.com/p/MKKRgodQ0WIIgL_R3QCgCRWCg30g22bXgxCdMk3YeKClB1238ZJXdau_Jsri0nzP/n/c4u04/b/qa-form/o/QA.docx) for details and let me know if you have any questions. Thanks!

**Comment by andytael** [comment]
Hello @arabellayao,
I've fixed the issues.

Thanks
Andy

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please fix the following issues of your PR:
1. Workshop's production in WMS is 8461, and it seems like you are updating files outside of this workshop. Please add the WMS IDs of all workshops that have been updated.
2. Use the [oracle-livelabs.github.io](http://oracle-livelabs.github.io/) links in index.html, instead of object storage links. Refer to this file for examples: https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop/workshops/tenancy/index.html

**Comment by andytael** [comment]
Closing PR to cleanup files that are not supposed to be in the PR

**Pull request closed without merging**
