### PR TITLE
Initial checkin of documentation for WMS #8461

### PR DESCRIPTION
**Pull request by andytael**
Initial checkin of documentation for WMS #8461

### CODE REVIEW

**Comment by malcherm** [comment]
Before we do the initial checkin - please make sure all file names are lower case and that there are no "_" underscores. Please use -

**Review by Brianna-Ambler — CHANGES_REQUESTED** [review]
Hi!

I have a few changes to request. They are as follows:

1. In your lab's markdown files, please ensure all sections align with what's detailed in the Self QA checklist. Specifically, the prerequisites section should have the leading line **_This lab assumes you have:_**. The objectives section should have the leading line _**In this lab, you will:**_.
2. In your manifest files, please ensure you are using the GitHub Pages (oracle-livelabs.github.io) link to the Get Started and Need Help files. There should not be object storage links being used for files that exist in the GitHub repo.
3. All filenames should be lowercase with dashes being used, rather than underscores. Please revisit the File Names section of our Self QA checklist (attached below) for more information on this.
[QA.docx](https://github.com/oracle-livelabs/converged/files/9223443/QA.docx)

**Comment by madhusudhanrao-ppm** [comment]
Please rename all the images to be lower case, remove _config folder, refer QA checklist document

image

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please fix the following issues of your PR:
1. Remove changes to _config.yml from your PR
2. Make sure all filenames are lower case
3. Make sure all filenames use dashes instead of underscores
4. Use the [oracle-livelabs.github.io](http://oracle-livelabs.github.io/) links in manifest.json and index.html, instead of learning-library links. Refer to these files for examples: https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop/workshops/tenancy

**Review by arabellayao — CHANGES_REQUESTED** [review]
Changes are not reflected. Please refer to the last comment. Please let me know if you need help. Thanks!

**Comment by arabellayao** [comment]
Hi! I am closing your PR, since it is open for a week, and you need to pull the latest changes from the oracle main branch. After you do that and new changes are ready, you can create a new PR. Thank you!

**Pull request closed without merging**
