### PR TITLE
Data Refactoring Advisor Livelab

### PR DESCRIPTION
**Pull request by praveennhiremath**
# 11016

# General requirements
1. Information in the workshop is adequate and updated - Verified.
2. Code is correct and working - Verified.
3. Links are correct - Verified.
4. Make sure you enter the help email link in your manifest.json - Verified.
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [x] All filenames are lower case (including folders, images, files, etc.)
- [x] Filenames are descriptive
- [x] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x] Image references in markdown contain an alternate text

### CODE REVIEW

**Comment by madhusudhanrao-ppm** [comment]
All image names and their extensions should be lowercase

image

**Comment by madhusudhanrao-ppm** [comment]
image

**Comment by praveennhiremath** [comment]
Hi Team,

I have fixed issues with file extensions being in uppercases. Do I need to raise a PR again for new changes or could you see my changes now?

Thanks,
Praveen Hiremath

From: Madhusudhan Rao ***@***.***>
Sent: Wednesday, October 26, 2022 5:35 PM
To: oracle-livelabs/converged ***@***.***>
Cc: PRAVEEN KUMAR HIREMATH ***@***.***>; Author ***@***.***>
Subject: [External] : Re: [oracle-livelabs/converged] Data Refactoring Advisor Livelab (PR #58)


All image names and their extensions should be lowercase

[Image removed by sender. image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/70625227/198021399-51f74c1c-965a-412e-8768-8bc5e5db9449.png__;!!ACWV5N9M2RV99hQ!NEB44SC4wof7v61x8JVNUrXPcPDVpK2tSfOfTd49MWdbF7qnlAT0h3dkw7UVxDVyPWt_7HAJy2eOC3fU2mapeC5LXn2O6n5r9Q$>

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please fix the following issues of your PR:
1. All images should have descriptive alternative texts in the Markdown files for accessibility
2. Use this index.html (copy the content) for your index.html: https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop/workshops/tenancy/index.html 
3. Use the [oracle-livelabs.github.io](http://oracle-livelabs.github.io/) links in manifest.json and index.html, instead of learning-library links. Refer to files in this directory for examples: https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop/workshops/tenancy

**Review by arabellayao — APPROVED** [review]

**Pull request merged**
