### PR TITLE
Requested Polishing #11025

### PR DESCRIPTION
**Pull request by RichardExley**
Requested by madhusudhan

### CODE REVIEW

**Comment by malcherm** [comment]
There are some conflicts that need to be resolved first.

**Review by arabellayao — DISMISSED** [review]
Hi! In the workshops/freetier/index.html, please replace "https://oracle.github.io/learning-library/common/redwood-hol/css/style.min.css" with "https://oracle-livelabs.github.io/common/redwood-hol/css/style.min.css", and replace "https://oracle.github.io/learning-library/common/redwood-hol/img/favicon.ico" with "https://oracle-livelabs.github.io/common/redwood-hol/img/favicon.ico". Thank you!

**Comment by RichardExley** [comment]
Changes to index.html completed

**Comment by RichardExley** [comment]
Changes made as requested

**Review by klazarz — APPROVED** [review]

**Review by klazarz — APPROVED** [review]

**Pull request merged**
